language: node_js

node_js:
  - "0.10"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

env:
  global:
    - TEST_FUNC_PORT=3030
    - TEST_FUNC_HOST=127.0.0.1
    - SAUCE_TUNNEL_ID=TRAVIS_WML_LITTLE_LOADER_${TRAVIS_JOB_NUMBER}
    - SAUCE_CONNECT_VERSION=4.3.10
    - SAUCE_USERNAME=wml-little-loader
    - secure: t9yalh16COfTgMWI58MKD5cq3/4t1jiiGmRz7xmi5T4QkRkxYzATF+C60z2nXbnsF4RLflcRBgJZ0PbR/L2JxQ3yALasougJjb0EbVr8XoJQiyhnUEQpRxtoxn9oV9Fnp3/DDQduPTZ1zPzd20N7mOpYoqNMaVnMFj353fVzI3vph29/uakvR/nNCq7BNjcOll5+JRifpXFgsACWUalU+IR/R1xmrciw7KoLlHfe8Zy349X0mv3Ez2uugqsQ5CZnRI9vffNvIWXhuVU0sCoANydYS+d5vBjO5txrxZSv14enXFKBLaXkxViYmzQMHI2FDjx71KsKeCoGoH9ooSOfwPSXSrUFTRDN0nhow3Z3uqo3EjP/uJ0I+Hoe7gJWvUDw90Q1IX2WuoSxWU+fdgEewZyvQboaC6CSaF2rdvCfl058uIbcGhhkkGAmpwvJKSsytWOJjeTA3hpYPSHGlvVLvXER1bfAIC/iBf5VGBExotNrPSpG+PsqzhpUsFSmkjY5gpKElhcNW9Ag3r5IJJJL1xVu8aXO55T5VrmTn/jINEAo91nJZhHrjX7x0kPWzlvU5/JAAOjpcrOVfpvqjkpvmxev/JtPZl2cx8lHadPXYJw98hIagpQdkfojNI5C4ACSrTVNe/IoEujgykbh9egpe8HGsG+U+g6qogmFPQFUP/8=

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Upgrade to npm v2
  - npm install -g npm@2

before_script:
  # Install dev. stuff (e.g., selenium drivers).
  - npm run install-dev

addons:
  sauce_connect: true

script:
  # Run all base checks.
  - npm run check-ci
  - npm run test-func-sauce
  # Safari runs into VM availability issues on Sauce.
  # Run as standalone, serially, and grepped to just the advanced build.
  # https://github.com/walmartlabs/little-loader/issues/5
  - npm run test-func-sauce-safari

  # Manually send coverage reports to coveralls.
  # TODO: COVERALLS
  # - ls  coverage/*/lcov.info | cat
  # - cat coverage/*/lcov.info | ./node_modules/.bin/coveralls || echo "Coveralls upload failed"
