language: node_js

node_js:
  - "0.10"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

env:
  global:
    - TEST_FUNC_PORT=3030
    - TEST_FUNC_HOST=127.0.0.1
    - SAUCE_CONNECT_TUNNEL_ID=$TRAVIS_JOB_NUMBER
    - SAUCE_USERNAME=wml-little-loader
    # TODO: FUNC TESTS
    #- secure: "TODO SECRETS"

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  # Install dev. stuff (e.g., selenium drivers).
  - npm run install-dev
  # TODO: FUNC TESTS
  # - nohup bash -c "node_modules/.bin/selenium-standalone start 2>&1 &"
  # - nohup bash -c "node_modules/.bin/http-server -a $TEST_FUNC_HOST -p $TEST_FUNC_PORT --silent 2>&1 &"

addons:
  sauce_connect: true

script:
  # Run all base checks.
  - npm run check-ci

  # Manually send coverage reports to coveralls.
  # TODO: COVERALLS
  # - ls  coverage/*/lcov.info | cat
  # - cat coverage/*/lcov.info | ./node_modules/.bin/coveralls || echo "Coveralls upload failed"
